AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  LockiServer

  Sample SAM Template for LockiServer

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Api:
    Cors:
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"  
  Function:
    Timeout: 120

Resources:
  GetNativeToken:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: getNativeTokenHandler.lambdaHandler
      Runtime: nodejs18.x
      MemorySize: 512
      Architectures:
      - x86_64
      Policies:
        # Give Create/Read/Update/Delete Permissions to the SampleTable
      - DynamoDBCrudPolicy:
          TableName: "locki-users"
      Environment:
        Variables:
          # Make table name accessible as environment variable from function code during execution
          LOCKI_USERS_TABLE: "locki-users"
          MUTLIVERSEX_API_URL: "https://devnet-api.multiversx.com"
      Events:
        GetNativeToken:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /identity
            Method: get
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
        - getNativeTokenHandler.ts
  
  GetDataNfts:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: getDataNftsHandler.lambdaHandler
      Runtime: nodejs18.x
      MemorySize: 512
      Architectures:
      - x86_64
      Policies:
        # Give Create/Read/Update/Delete Permissions to the SampleTable
      - DynamoDBCrudPolicy:
          TableName: "locki-users"
      Environment:
        Variables:
          # Make table name accessible as environment variable from function code during execution
          LOCKI_USERS_TABLE: "locki-users"
          MUTLIVERSEX_API_URL: "https://devnet-api.multiversx.com"
          NFT_COLLECTION: "DATANFTFT4-3ba099"
      Events:
        GetDataNfts:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /datanfts
            Method: get
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
        - getDataNftsHandler.ts
        External:
        - "@aws-sdk/lib-dynamodb"
        - "@aws-sdk/client-dynamodb"
  
  GeneratePreviewModel:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: generatePreviewModelHandler.lambdaHandler
      Runtime: nodejs18.x
      MemorySize: 512
      Architectures:
      - x86_64
      Policies:
        # Give Create/Read/Update/Delete Permissions to the SampleTable
      - SQSSendMessagePolicy:
          QueueName: !GetAtt ScriptsProcessingQueue.QueueName
      - S3CrudPolicy:
          BucketName: 'blender-scripts'
      - S3CrudPolicy:
          BucketName: 'dataassets.locki.io'
      - DynamoDBCrudPolicy:
          TableName: 'scripts-processing-history'
      Environment:
        Variables:
          SCRIPTS_PROCESSING_QUEUE: !GetAtt ScriptsProcessingQueue.QueueUrl
          SCRIPTS_PROCESSING_BUCKET: '{{resolve:ssm:SCRIPTS_PROCESSING_BUCKET}}'
          SCRIPTS_PROCESSING_HISTORY_TABLE: 'scripts-processing-history'
      Events:
        MintBlenderScripts:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /generatePreview
            Method: post
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
        - generatePreviewModelHandler.ts
        External:
        - "@aws-sdk"
  
  ScriptsProcessor:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: scriptsProcessor.lambdaHandler
      Runtime: nodejs18.x
      MemorySize: 512
      Architectures:
      - x86_64
      Policies:
        # Give Create/Read/Update/Delete Permissions to the SampleTable
      - Version: '2012-10-17' 
        Statement:
          - Effect: Allow
            Action:
              - ec2:RunInstances
              - ec2:TerminateInstances
            Resource: '*'
          - Effect: Allow
            Action:
              - execute-api:ManageConnections
            Resource: '*'
      - S3CrudPolicy:
          BucketName: 'blender-scripts'
      - S3CrudPolicy:
          BucketName: 'dataassets.locki.io'
      - DynamoDBCrudPolicy:
          TableName: 'scripts-processing-history'
      - DynamoDBReadPolicy:
          TableName: 'locki-socket-connection-history'
      - SQSSendMessagePolicy:
          QueueName: !GetAtt ScriptsProcessingQueue.QueueName
      Environment:
        Variables:
          BLENDER_PROCESSOR_INSTANCE_IMAGE_ID: '{{resolve:ssm:BLENDER_PROCESSOR_INSTANCE_IMAGE_ID}}'
          BLENDER_PROCESSOR_INSTANCE_SG: '{{resolve:ssm:BLENDER_PROCESSOR_INSTANCE_SG}}'
          SCRIPTS_PROCESSING_BUCKET: '{{resolve:ssm:SCRIPTS_PROCESSING_BUCKET}}'
          SCRIPTS_PROCESSING_HISTORY_TABLE: 'scripts-processing-history'
          SCRIPTS_PROCESSING_QUEUE: !GetAtt ScriptsProcessingQueue.QueueUrl
          CONNECTION_TABLE_NAME: '{{resolve:ssm:CONNECTION_TABLE_NAME}}'
          WEBSOCKET_ENDPOINT: '{{resolve:ssm:WEBSOCKET_ENDPOINT}}'
      Events:
        MintBlenderSqsEvent:
          Type: SQS # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Queue: !GetAtt ScriptsProcessingQueue.Arn
            BatchSize: 1
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
        - scriptsProcessor.ts
        External:
        - "@aws-sdk"
  
  LockiUsers:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "address"
          AttributeType: "S"
        - AttributeName: "origin"
          AttributeType: "S"
        - AttributeName: "apiKey"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "address"
          KeyType: "HASH"
        - AttributeName: "origin"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
      GlobalSecondaryIndexes:
        - IndexName: "apiKey_ix"
          KeySchema:
          - AttributeName: "apiKey"
            KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
          ProvisionedThroughput:
            ReadCapacityUnits: 2
            WriteCapacityUnits: 2
      TableName: "locki-users"

  ScriptsProcessingHistory:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "N"
        - AttributeName: "type"
          AttributeType: "S"
        - AttributeName: "filename"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
        - AttributeName: "type"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
      GlobalSecondaryIndexes:
        - IndexName: "filename_type_ix"
          KeySchema:
          - AttributeName: "filename"
            KeyType: "HASH"
          - AttributeName: "type"
            KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
          ProvisionedThroughput:
            ReadCapacityUnits: 2
            WriteCapacityUnits: 2
      TableName: "scripts-processing-history"
  
  ScriptsProcessingQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 120

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  GetNativeTokenFunction:
    Description: Get Native Auth Token API
    Value: !GetAtt GetNativeToken.Arn
  GetDataNftsFunction:
    Description: Get Data Nfts for the current user based on the native auth token
    Value: !GetAtt GetDataNfts.Arn
  GeneratePreviewModalFunction:
    Description: Generate Preview of the 3D modal from the script provided
    Value: !GetAtt GeneratePreviewModel.Arn
