AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  LockiServer

  Sample SAM Template for LockiServer

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Api:
    Cors:
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"  
  Function:
    Timeout: 120

Resources:
  GetNativeToken:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      MemorySize: 256
      Architectures:
      - x86_64
      Policies:
        # Give Create/Read/Update/Delete Permissions to the SampleTable
      - DynamoDBCrudPolicy:
          TableName: "locki-users"
      Environment:
        Variables:
          # Make table name accessible as environment variable from function code during execution
          LOCKI_USERS_TABLE: "locki-users"
          MUTLIVERSEX_API_URL: "https://devnet-api.multiversx.com"
      Events:
        GetNativeToken:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /identity
            Method: get
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
        - app.ts
        External:
        - "@aws-sdk/lib-dynamodb"
        - "@aws-sdk/client-dynamodb"
  
  GetDataNfts:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      MemorySize: 256
      Architectures:
      - x86_64
      Policies:
        # Give Create/Read/Update/Delete Permissions to the SampleTable
      - DynamoDBCrudPolicy:
          TableName: "locki-users"
      Environment:
        Variables:
          # Make table name accessible as environment variable from function code during execution
          LOCKI_USERS_TABLE: "locki-users"
          MUTLIVERSEX_API_URL: "https://devnet-api.multiversx.com"
          NFT_COLLECTION: "DATANFTFT4-3ba099"
      Events:
        GetDataNfts:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /datanfts
            Method: get
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
        - app.ts
        External:
        - "@aws-sdk/lib-dynamodb"
        - "@aws-sdk/client-dynamodb"
  
  MintBlenderScripts:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      MemorySize: 512
      Architectures:
      - x86_64
      Policies:
        # Give Create/Read/Update/Delete Permissions to the SampleTable
      - DynamoDBCrudPolicy:
          TableName: "locki-users"
      # Environment:
        # Variables:
          # Make table name accessible as environment variable from function code during execution
          # LOCKI_USERS_TABLE: "locki-users"
          # MUTLIVERSEX_API_URL: "https://devnet-api.multiversx.com"
          # NFT_COLLECTION: "DATANFTFT4-3ba099"
      Events:
        MintBlenderScripts:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /mintBlenderScripts
            Method: post
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
        - app.ts
        External:
        - "@aws-sdk"
  
  LockiUsers:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "address"
          AttributeType: "S"
        - AttributeName: "origin"
          AttributeType: "S"
        - AttributeName: "apiKey"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "address"
          KeyType: "HASH"
        - AttributeName: "origin"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
      GlobalSecondaryIndexes:
        - IndexName: "apiKey_ix"
          KeySchema:
          - AttributeName: "apiKey"
            KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
          ProvisionedThroughput:
            ReadCapacityUnits: 2
            WriteCapacityUnits: 2
      TableName: "locki-users"

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  GetNativeTokenApi:
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  GetNativeTokenFunction:
    Description: Hello World Lambda Function ARN
    Value: !GetAtt GetNativeToken.Arn
